version: '3'
services:
  order-service:
    build: ./
    environment:
      OTEL_SERVICE_NAME: "user-service"
      OTEL_TRACES_EXPORTER: "jaeger,zipkin,logging"
      OTEL_EXPORTER_JAEGER_ENDPOINT: "http://jaeger:14250"
      OTEL_EXPORTER_ZIPKIN_ENDPOINT: "http://zipkin:9411/api/v2/spans"
      OTEL_LOGS_EXPORTER: "logging"
      OTEL_METRICS_EXPORTER: "logging"
    ports:
      - "8083:8083"
